In [1]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [2]:

from transformers import pipeline
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = 0)
classifier("I love this!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

c:\Users\tiffa\projects\nextUp\.venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\tiffa\.cache\huggingface\hub\models--j-hartmann--emotion-english-distilroberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  329MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  329MB

model.safetensors: downloading bytes:           |  0.00B

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528691716492176},
  {'label': 'neutral', 'score': 0.005764589179307222},
  {'label': 'anger', 'score': 0.004419785924255848},
  {'label': 'sadness', 'score': 0.002092391485348344},
  {'label': 'disgust', 'score': 0.0016119893407449126},
  {'label': 'fear', 'score': 0.0004138525982853025}]]

In [3]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [ ]:
# Classify based on entire description
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.654840350151062},
  {'label': 'neutral', 'score': 0.1698523759841919},
  {'label': 'sadness', 'score': 0.11640935391187668},
  {'label': 'surprise', 'score': 0.020700646564364433},
  {'label': 'disgust', 'score': 0.01910071261227131},
  {'label': 'joy', 'score': 0.015161429531872272},
  {'label': 'anger', 'score': 0.003935148473829031}]]

In [5]:
# Classify by each sentence
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296019792556763},
  {'label': 'neutral', 'score': 0.14038611948490143},
  {'label': 'fear', 'score': 0.06816230714321136},
  {'label': 'joy', 'score': 0.04794260114431381},
  {'label': 'anger', 'score': 0.00915636494755745},
  {'label': 'disgust', 'score': 0.0026284789200872183},
  {'label': 'sadness', 'score': 0.002122164238244295}],
 [{'label': 'neutral', 'score': 0.4493708610534668},
  {'label': 'disgust', 'score': 0.2735908329486847},
  {'label': 'joy', 'score': 0.10908335447311401},
  {'label': 'sadness', 'score': 0.09362750500440598},
  {'label': 'anger', 'score': 0.04047827795147896},
  {'label': 'surprise', 'score': 0.026970183476805687},
  {'label': 'fear', 'score': 0.006879052612930536}],
 [{'label': 'neutral', 'score': 0.646215558052063},
  {'label': 'sadness', 'score': 0.24273371696472168},
  {'label': 'disgust', 'score': 0.04342271387577057},
  {'label': 'surprise', 'score': 0.028300553560256958},
  {'label': 'joy', 'score': 0.014211495406925678},
  {'label': 'fear', 'score': 0.014084100723266602},
  {'label': 'anger', 'score': 0.011031909845769405}],
 [{'label': 'fear', 'score': 0.9281682968139648},
  {'label': 'anger', 'score': 0.032190851867198944},
  {'label': 'neutral', 'score': 0.012808678671717644},
  {'label': 'sadness', 'score': 0.008756862953305244},
  {'label': 'surprise', 'score': 0.00859790574759245},
  {'label': 'disgust', 'score': 0.008431815542280674},
  {'label': 'joy', 'score': 0.0010455832816660404}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104134567081928},
  {'label': 'disgust', 'score': 0.006480589509010315},
  {'label': 'fear', 'score': 0.005393982399255037},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.0018428878393024206},
  {'label': 'joy', 'score': 0.001733877114020288}],
 [{'label': 'joy', 'score': 0.9327981472015381},
  {'label': 'disgust', 'score': 0.03771703690290451},
  {'label': 'neutral', 'score': 0.015891805291175842},
  {'label': 'sadness', 'score': 0.006444500293582678},
  {'label': 'anger', 'score': 0.005024963524192572},
  {'label': 'surprise', 'score': 0.00158120587002486},
  {'label': 'fear', 'score': 0.0005423059337772429}],
 [{'label': 'joy', 'score': 0.6528708338737488},
  {'label': 'neutral', 'score': 0.2542746663093567},
  {'label': 'surprise', 'score': 0.06808291375637054},
  {'label': 'sadness', 'score': 0.009908990934491158},
  {'label': 'disgust', 'score': 0.006512216292321682},
  {'label': 'anger', 'score': 0.004821304697543383},
  {'label': 'fear', 'score': 0.0035290175583213568}],
 [{'label': 'neutral', 'score': 0.5494767427444458},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400668531656265},
  {'label': 'surprise', 'score': 0.07876549661159515},
  {'label': 'anger', 'score': 0.0641336441040039},
  {'label': 'fear', 'score': 0.051362842321395874},
  {'label': 'joy', 'score': 0.04056442528963089}]]

In [6]:
# Comparing sentences to the predictions
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [7]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [8]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296019792556763},
 {'label': 'neutral', 'score': 0.14038611948490143},
 {'label': 'fear', 'score': 0.06816230714321136},
 {'label': 'joy', 'score': 0.04794260114431381},
 {'label': 'anger', 'score': 0.00915636494755745},
 {'label': 'disgust', 'score': 0.0026284789200872183},
 {'label': 'sadness', 'score': 0.002122164238244295}]

In [10]:
# Analyzing another sentence (e.g., 4th sentence)
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [11]:
predictions[3]

[{'label': 'fear', 'score': 0.9281682968139648},
 {'label': 'anger', 'score': 0.032190851867198944},
 {'label': 'neutral', 'score': 0.012808678671717644},
 {'label': 'sadness', 'score': 0.008756862953305244},
 {'label': 'surprise', 'score': 0.00859790574759245},
 {'label': 'disgust', 'score': 0.008431815542280674},
 {'label': 'joy', 'score': 0.0010455832816660404}]

In [12]:
predictions

[[{'label': 'surprise', 'score': 0.7296019792556763},
  {'label': 'neutral', 'score': 0.14038611948490143},
  {'label': 'fear', 'score': 0.06816230714321136},
  {'label': 'joy', 'score': 0.04794260114431381},
  {'label': 'anger', 'score': 0.00915636494755745},
  {'label': 'disgust', 'score': 0.0026284789200872183},
  {'label': 'sadness', 'score': 0.002122164238244295}],
 [{'label': 'neutral', 'score': 0.4493708610534668},
  {'label': 'disgust', 'score': 0.2735908329486847},
  {'label': 'joy', 'score': 0.10908335447311401},
  {'label': 'sadness', 'score': 0.09362750500440598},
  {'label': 'anger', 'score': 0.04047827795147896},
  {'label': 'surprise', 'score': 0.026970183476805687},
  {'label': 'fear', 'score': 0.006879052612930536}],
 [{'label': 'neutral', 'score': 0.646215558052063},
  {'label': 'sadness', 'score': 0.24273371696472168},
  {'label': 'disgust', 'score': 0.04342271387577057},
  {'label': 'surprise', 'score': 0.028300553560256958},
  {'label': 'joy', 'score': 0.014211495406925678},
  {'label': 'fear', 'score': 0.014084100723266602},
  {'label': 'anger', 'score': 0.011031909845769405}],
 [{'label': 'fear', 'score': 0.9281682968139648},
  {'label': 'anger', 'score': 0.032190851867198944},
  {'label': 'neutral', 'score': 0.012808678671717644},
  {'label': 'sadness', 'score': 0.008756862953305244},
  {'label': 'surprise', 'score': 0.00859790574759245},
  {'label': 'disgust', 'score': 0.008431815542280674},
  {'label': 'joy', 'score': 0.0010455832816660404}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104134567081928},
  {'label': 'disgust', 'score': 0.006480589509010315},
  {'label': 'fear', 'score': 0.005393982399255037},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.0018428878393024206},
  {'label': 'joy', 'score': 0.001733877114020288}],
 [{'label': 'joy', 'score': 0.9327981472015381},
  {'label': 'disgust', 'score': 0.03771703690290451},
  {'label': 'neutral', 'score': 0.015891805291175842},
  {'label': 'sadness', 'score': 0.006444500293582678},
  {'label': 'anger', 'score': 0.005024963524192572},
  {'label': 'surprise', 'score': 0.00158120587002486},
  {'label': 'fear', 'score': 0.0005423059337772429}],
 [{'label': 'joy', 'score': 0.6528708338737488},
  {'label': 'neutral', 'score': 0.2542746663093567},
  {'label': 'surprise', 'score': 0.06808291375637054},
  {'label': 'sadness', 'score': 0.009908990934491158},
  {'label': 'disgust', 'score': 0.006512216292321682},
  {'label': 'anger', 'score': 0.004821304697543383},
  {'label': 'fear', 'score': 0.0035290175583213568}],
 [{'label': 'neutral', 'score': 0.5494767427444458},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400668531656265},
  {'label': 'surprise', 'score': 0.07876549661159515},
  {'label': 'anger', 'score': 0.0641336441040039},
  {'label': 'fear', 'score': 0.051362842321395874},
  {'label': 'joy', 'score': 0.04056442528963089}]]

In [13]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.00915636494755745},
 {'label': 'disgust', 'score': 0.0026284789200872183},
 {'label': 'fear', 'score': 0.06816230714321136},
 {'label': 'joy', 'score': 0.04794260114431381},
 {'label': 'neutral', 'score': 0.14038611948490143},
 {'label': 'sadness', 'score': 0.002122164238244295},
 {'label': 'surprise', 'score': 0.7296019792556763}]

In [31]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels} # all of the scores for every single description for each of the labels

# Extract maximum emotion probability for each
def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels} # holds all of the predictions for a particular description
    # loop through each of the sentences
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [32]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [33]:
emotion_scores

{'anger': [np.float64(0.0641336441040039),
  np.float64(0.6126196980476379),
  np.float64(0.0641336441040039),
  np.float64(0.35148391127586365),
  np.float64(0.08141252398490906),
  np.float64(0.23222488164901733),
  np.float64(0.5381841659545898),
  np.float64(0.0641336441040039),
  np.float64(0.30066978931427),
  np.float64(0.0641336441040039)],
 'disgust': [np.float64(0.2735908329486847),
  np.float64(0.34828439354896545),
  np.float64(0.10400668531656265),
  np.float64(0.15072239935398102),
  np.float64(0.18449558317661285),
  np.float64(0.7271748185157776),
  np.float64(0.1558549404144287),
  np.float64(0.10400668531656265),
  np.float64(0.27948111295700073),
  np.float64(0.17792651057243347)],
 'fear': [np.float64(0.9281682968139648),
  np.float64(0.942527711391449),
  np.float64(0.9723208546638489),
  np.float64(0.3607065677642822),
  np.float64(0.09504339098930359),
  np.float64(0.051362842321395874),
  np.float64(0.7474274635314941),
  np.float64(0.40449729561805725),
  np.float64(0.9155240654945374),
  np.float64(0.051362842321395874)],
 'joy': [np.float64(0.9327981472015381),
  np.float64(0.7044220566749573),
  np.float64(0.7672383189201355),
  np.float64(0.2518812119960785),
  np.float64(0.04056442528963089),
  np.float64(0.043375834822654724),
  np.float64(0.8725656270980835),
  np.float64(0.04056442528963089),
  np.float64(0.04056442528963089),
  np.float64(0.04056442528963089)],
 'sadness': [np.float64(0.646215558052063),
  np.float64(0.8879395127296448),
  np.float64(0.5494767427444458),
  np.float64(0.7326850891113281),
  np.float64(0.8843896985054016),
  np.float64(0.621391773223877),
  np.float64(0.7121939659118652),
  np.float64(0.5494767427444458),
  np.float64(0.8402893543243408),
  np.float64(0.8603723645210266)],
 'surprise': [np.float64(0.9671575427055359),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.47588032484054565),
  np.float64(0.11169017851352692),
  np.float64(0.4080010652542114),
  np.float64(0.8202826380729675),
  np.float64(0.3544614315032959),
  np.float64(0.11169017851352692)],
 'neutral': [np.float64(0.7296019792556763),
  np.float64(0.2525463104248047),
  np.float64(0.07876549661159515),
  np.float64(0.07876549661159515),
  np.float64(0.07876549661159515),
  np.float64(0.2719035744667053),
  np.float64(0.07876549661159515),
  np.float64(0.23448717594146729),
  np.float64(0.13561399281024933),
  np.float64(0.07876549661159515)]}

In [34]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [16:31<00:00,  5.24it/s]

In [35]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [36]:
emotions_df # will see separate columns for each of the emotions, with each containing max probability for that description

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928168,0.932798,0.646216,0.967158,0.729602,9780002005883
1,0.612620,0.348284,0.942528,0.704422,0.887940,0.111690,0.252546,9780002261982
2,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078765,9780006178736
3,0.351484,0.150722,0.360707,0.251881,0.732685,0.111690,0.078765,9780006280897
4,0.081413,0.184496,0.095043,0.040564,0.884390,0.475880,0.078765,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148208,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765,9788173031014
5194,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459269,0.759456,0.951104,0.368110,0.078765,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765,9789027712059

In [37]:
books = pd.merge(books, emotions_df, on = "isbn13")

In [38]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,sadness_x,surprise_x,neutral_x,anger_y,disgust_y,fear_y,joy_y,sadness_y,surprise_y,neutral_y
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,0.646216,0.967158,0.729602,0.064134,0.273591,0.928168,0.932798,0.646216,0.967158,0.729602
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.887940,0.111690,0.252546,0.612620,0.348284,0.942528,0.704422,0.887940,0.111690,0.252546
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,0.549477,0.111690,0.078765,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,0.732685,0.111690,0.078765,0.351484,0.150722,0.360707,0.251881,0.732685,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,0.884390,0.475880,0.078765,0.081413,0.184496,0.095043,0.040564,0.884390,0.475880,0.078765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,0.853721,0.980877,0.030656,0.148208,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,0.883198,0.111690,0.227765,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,0.375754,0.066685,0.057625,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,0.951104,0.368110,0.078765,0.064134,0.104007,0.459269,0.759456,0.951104,0.368110,0.078765
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,0.915193,0.111690,0.078765,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765

In [39]:
books.to_csv("books_with_emotions.csv", index = False)